### PR TITLE
completed hero section

### PR DESCRIPTION
**Pull request by OlaOluwalekan**
completed hero section including image slides

hero2
hero1

### CODE REVIEW

**Comment by imendy** [comment]
nice work, but is the hero section a slider or a carousel?

**Comment by OlaOluwalekan** [comment]
> nice work, but is the hero section a slider or a carousel?

carousel actually. Slider is just much more a common term

**Comment by imendy** [comment]
okay nice

**Review by imendy — APPROVED** [review]
nice

**Pull request merged**
